# -*- coding: utf-8 -*-
"""SokobanPonderado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX2p6GD4753wTq4WcDBzE9iwGmRf8YmE
"""

import heapq
from collections import deque
import time
import sys

# CLASSE ESTADO

class Estado:
    """
    Representa um estado do jogo Sokoban.

    Atributos:
        agente (tuple): Posição (x, y) do agente
        caixas (list): Lista de tuplas (x, y, peso) para cada caixa
        alvos (list): Lista de tuplas (x, y) com posições dos alvos
        barreiras (set): Conjunto de tuplas (x, y) com posições das barreiras
    """

    def __init__(self, agente, caixas, alvos, barreiras):
        self.agente = tuple(agente)
        self.caixas = [(x, y, p) for x, y, p in caixas]
        self.alvos = [tuple(a) for a in alvos]
        self.barreiras = set(tuple(b) for b in barreiras)

        # Cache para hash (otimização)
        self._hash = None
        self._caixas_tuple = None

    def __hash__(self):
        """Hash baseado na posição do agente e posições das caixas."""
        if self._hash is None:
            # Ordena as caixas para hash consistente
            caixas_pos = sorted((x, y) for x, y, _ in self.caixas)
            self._caixas_tuple = tuple(caixas_pos)
            self._hash = hash((self.agente, self._caixas_tuple))
        return self._hash

    def __eq__(self, other):
        """Compara dois estados (ignora pesos para igualdade de posição)."""
        if not isinstance(other, Estado):
            return False

        if self.agente != other.agente:
            return False

        # Compara apenas posições das caixas, não os pesos
        self_pos = {(x, y) for x, y, _ in self.caixas}
        other_pos = {(x, y) for x, y, _ in other.caixas}
        return self_pos == other_pos

    def __lt__(self, other):
        """Necessário para usar heapq com estados."""
        return False  # Não usado diretamente

    def __str__(self):
        """Cria representação visual do grid."""
        # Encontra dimensões do grid
        max_x = max(
            self.agente[0],
            max((x for x, _, _ in self.caixas), default=0),
            max((x for x, _ in self.alvos), default=0),
            max((x for x, _ in self.barreiras), default=0)
        ) + 1

        max_y = max(
            self.agente[1],
            max((y for _, y, _ in self.caixas), default=0),
            max((y for _, y in self.alvos), default=0),
            max((y for _, y in self.barreiras), default=0)
        ) + 1

        # Cria grid vazio
        grid = [['⚪️' for _ in range(max_x)] for _ in range(max_y)]

        # Adiciona barreiras
        for x, y in self.barreiras:
            if 0 <= y < max_y and 0 <= x < max_x:
                grid[y][x] = '🧱'

        # Adiciona alvos
        for x, y in self.alvos:
            if 0 <= y < max_y and 0 <= x < max_x:
                grid[y][x] = '🎯'

        # Adiciona caixas (sobrescreve alvos se necessário)
        for x, y, peso in self.caixas:
            if 0 <= y < max_y and 0 <= x < max_x:
                if (x, y) in self.alvos:
                    grid[y][x] = f'✅'  # Caixa no alvo
                else:
                    grid[y][x] = f'📦({peso})'

        # Adiciona agente (sobrescreve se necessário)
        x, y = self.agente
        if 0 <= y < max_y and 0 <= x < max_x:
            if (x, y) in [pos for pos, _, _ in self.caixas]:
                grid[y][x] = '🤖📦'  # Agente sobre caixa (não deveria acontecer)
            else:
                grid[y][x] = '🤖'

        # Converte para string
        return '\n'.join(' '.join(linha) for linha in grid)

    def copiar(self):
        """Cria uma cópia profunda do estado."""
        return Estado(
            self.agente,
            [(x, y, p) for x, y, p in self.caixas],
            self.alvos[:],
            self.barreiras.copy()
        )

# FUNÇÕES AUXILIARES

def ler_arquivo(nome_arquivo):
    """
    Lê o arquivo de entrada e cria o estado inicial.

    Formato esperado:
    - ⚪️ : espaço vazio
    - 🧱 : barreira
    - 🤖 : agente
    - 📦(n) : caixa com peso n
    - 🎯 : alvo

    Args:
        nome_arquivo (str): Caminho para o arquivo de entrada

    Returns:
        Estado: Estado inicial do problema
    """
    with open(nome_arquivo, 'r', encoding='utf-8') as f:
        linhas = [linha.strip().split() for linha in f.readlines()]

    agente = None
    caixas = []
    alvos = []
    barreiras = []

    for y, linha in enumerate(linhas):
        for x, celula in enumerate(linha):
            if celula == '🤖':
                agente = (x, y)
            elif celula.startswith('📦'):
                # Extrai peso da caixa (formato: 📦(5))
                peso = int(celula[2:-1])  # Remove '📦(' e ')'
                caixas.append((x, y, peso))
            elif celula == '🎯':
                alvos.append((x, y))
            elif celula == '🧱':
                barreiras.append((x, y))
            # ⚪️ é ignorado (vazio)

    if agente is None:
        raise ValueError("Arquivo não contém agente (🤖)")

    return Estado(agente, caixas, alvos, barreiras)


def eh_posicao_valida(x, y, estado):
    """
    Verifica se uma posição é válida para movimento.

    Args:
        x, y (int): Coordenadas
        estado (Estado): Estado atual

    Returns:
        bool: True se a posição é válida (dentro do grid e não é barreira)
    """
    # Verifica limites do grid (assume grid retangular baseado nas barreiras)
    if estado.barreiras:
        max_x = max(max(x for x, _ in estado.barreiras), estado.agente[0],
                   max((x for x, _, _ in estado.caixas), default=0),
                   max((x for x, _ in estado.alvos), default=0)) + 2
        max_y = max(max(y for _, y in estado.barreiras), estado.agente[1],
                   max((y for _, y, _ in estado.caixas), default=0),
                   max((y for _, y in estado.alvos), default=0)) + 2
    else:
        # Se não há barreiras, usa posições das caixas/alvos para definir limites
        max_x = max(estado.agente[0],
                   max((x for x, _, _ in estado.caixas), default=0),
                   max((x for x, _ in estado.alvos), default=0)) + 2
        max_y = max(estado.agente[1],
                   max((y for _, y, _ in estado.caixas), default=0),
                   max((y for _, y in estado.alvos), default=0)) + 2

    if x < 0 or y < 0 or x >= max_x or y >= max_y:
        return False

    return (x, y) not in estado.barreiras


def encontrar_caixa(posicao, caixas):
    """
    Encontra uma caixa em determinada posição.

    Args:
        posicao (tuple): (x, y) a verificar
        caixas (list): Lista de caixas [(x, y, peso)]

    Returns:
        tuple or None: A caixa (x, y, peso) se encontrada, None caso contrário
    """
    for caixa in caixas:
        if (caixa[0], caixa[1]) == posicao:
            return caixa
    return None


def heuristica(estado):
    """
    Calcula a heurística para um estado.

    A heurística é a soma das distâncias de Manhattan de cada caixa
    ao alvo mais próximo, multiplicada pelo peso da caixa.

    Args:
        estado (Estado): Estado atual

    Returns:
        int: Valor heurístico (sempre ≤ custo real)
    """
    custo_estimado = 0
    alvos_disponiveis = estado.alvos.copy()

    # Ordena caixas por peso (mais pesadas primeiro - melhora a heurística)
    caixas_ordenadas = sorted(estado.caixas, key=lambda c: -c[2])

    for x_caixa, y_caixa, peso in caixas_ordenadas:
        if not alvos_disponiveis:
            break

        # Calcula distância para todos os alvos disponíveis
        distancias = []
        for x_alvo, y_alvo in alvos_disponiveis:
            dist = abs(x_caixa - x_alvo) + abs(y_caixa - y_alvo)
            distancias.append((dist, (x_alvo, y_alvo)))

        # Encontra o alvo mais próximo
        if distancias:
            dist_min, alvo_escolhido = min(distancias, key=lambda x: x[0])

            # Adiciona ao custo estimado
            custo_estimado += dist_min * peso

            # Remove o alvo escolhido
            alvos_disponiveis.remove(alvo_escolhido)

    return custo_estimado


def calcular_custo_acao(estado_anterior, estado_novo):
    """
    Calcula o custo de uma ação baseado nas caixas movidas.

    Args:
        estado_anterior (Estado): Estado antes da ação
        estado_novo (Estado): Estado depois da ação

    Returns:
        int: Custo da ação (1 para movimento simples, 1+peso para empurrar)
    """
    # Verifica se alguma caixa foi movida
    for i, (x_ant, y_ant, peso_ant) in enumerate(estado_anterior.caixas):
        x_novo, y_novo, _ = estado_novo.caixas[i]
        if (x_ant, y_ant) != (x_novo, y_novo):
            return 1 + peso_ant  # Custo com caixa

    return 1  # Custo de movimento simples


def gerar_sucessores(estado):
    """
    Gera todos os estados sucessores válidos a partir do estado atual.

    Args:
        estado (Estado): Estado atual

    Returns:
        list: Lista de tuplas (estado_sucessor, tipo_acao, peso_caixa)
               tipo_acao: 'mover' ou 'empurrar'
               peso_caixa: 0 para movimento, peso da caixa para empurrar
    """
    sucessores = []
    direcoes = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # cima, baixo, esq, dir

    x_agente, y_agente = estado.agente

    for dx, dy in direcoes:
        nova_x = x_agente + dx
        nova_y = y_agente + dy

        # Verifica se a nova posição é válida
        if not eh_posicao_valida(nova_x, nova_y, estado):
            continue

        # Verifica se há caixa na nova posição
        caixa = encontrar_caixa((nova_x, nova_y), estado.caixas)

        if caixa:
            # Movimento com caixa (empurrar)
            caixa_x, caixa_y, peso = caixa
            nova_caixa_x = caixa_x + dx
            nova_caixa_y = caixa_y + dy

            # Verifica se a posição atrás da caixa é válida
            if not eh_posicao_valida(nova_caixa_x, nova_caixa_y, estado):
                continue

            # Verifica se não há outra caixa atrás
            if encontrar_caixa((nova_caixa_x, nova_caixa_y), estado.caixas):
                continue

            # Cria novo estado com a caixa movida
            novo_estado = estado.copiar()
            novo_estado.agente = (nova_x, nova_y)

            # Atualiza posição da caixa
            novas_caixas = []
            for cx, cy, cp in novo_estado.caixas:
                if (cx, cy) == (caixa_x, caixa_y):
                    novas_caixas.append((nova_caixa_x, nova_caixa_y, cp))
                else:
                    novas_caixas.append((cx, cy, cp))
            novo_estado.caixas = novas_caixas

            sucessores.append((novo_estado, 'empurrar', peso))

        else:
            # Movimento simples
            novo_estado = estado.copiar()
            novo_estado.agente = (nova_x, nova_y)
            sucessores.append((novo_estado, 'mover', 0))

    return sucessores


def eh_estado_objetivo(estado):
    """
    Verifica se um estado é objetivo (todas as caixas em alvos).

    Args:
        estado (Estado): Estado a verificar

    Returns:
        bool: True se todas as caixas estão em alvos
    """
    # Se número de caixas diferente de número de alvos, não pode ser objetivo
    if len(estado.caixas) != len(estado.alvos):
        return False

    # Verifica se cada caixa está em um alvo
    posicoes_caixas = {(x, y) for x, y, _ in estado.caixas}
    return all(pos in estado.alvos for pos in posicoes_caixas)


def reconstruir_caminho(veio_de, estado_final):
    """
    Reconstrói o caminho de estados do início até o objetivo.

    Args:
        veio_de (dict): Dicionário mapeando estado -> (estado_anterior, acao, peso)
        estado_final (Estado): Estado objetivo

    Returns:
        list: Lista de estados no caminho
    """
    caminho = []
    estado_atual = estado_final

    while estado_atual in veio_de:
        caminho.append(estado_atual)
        estado_atual, _, _ = veio_de[estado_atual]

    caminho.append(estado_atual)  # Adiciona estado inicial
    return list(reversed(caminho))

# ALGORITMOS DE BUSCA

def dijkstra(estado_inicial, max_iter=100000):
    """
    Algoritmo de Dijkstra (custo uniforme).

    Args:
        estado_inicial (Estado): Estado inicial
        max_iter (int): Número máximo de iterações

    Returns:
        tuple: (custo, estado_final, stats) onde stats é um dicionário com
               métricas de desempenho
    """
    print("Executando Dijkstra...")
    inicio = time.time()

    # Fronteira: (custo_acumulado, contador, estado)
    contador = 0
    fronteira = [(0, contador, estado_inicial)]
    heapq.heapify(fronteira)

    # Dicionários para controle
    custos = {estado_inicial: 0}
    veio_de = {}  # estado -> (estado_anterior, acao, peso)
    visitados = set()

    iteracoes = 0
    max_fronteira = 1

    while fronteira and iteracoes < max_iter:
        iteracoes += 1
        custo_atual, _, estado_atual = heapq.heappop(fronteira)

        # Atualiza estatísticas
        max_fronteira = max(max_fronteira, len(fronteira))

        # Se já visitamos este estado com custo menor, ignora
        if estado_atual in visitados:
            continue

        visitados.add(estado_atual)

        # Verifica se é objetivo
        if eh_estado_objetivo(estado_atual):
            fim = time.time()
            stats = {
                'iteracoes': iteracoes,
                'visitados': len(visitados),
                'max_fronteira': max_fronteira,
                'tempo': fim - inicio
            }
            return custo_atual, estado_atual, stats

        # Gera sucessores
        for sucessor, acao, peso in gerar_sucessores(estado_atual):
            custo_acao = 1 if acao == 'mover' else 1 + peso
            novo_custo = custo_atual + custo_acao

            if sucessor not in custos or novo_custo < custos[sucessor]:
                custos[sucessor] = novo_custo
                contador += 1
                heapq.heappush(fronteira, (novo_custo, contador, sucessor))
                veio_de[sucessor] = (estado_atual, acao, peso)

    fim = time.time()
    stats = {
        'iteracoes': iteracoes,
        'visitados': len(visitados),
        'max_fronteira': max_fronteira,
        'tempo': fim - inicio
    }
    return float('inf'), None, stats


def ganancioso(estado_inicial, max_iter=100000):
    """
    Algoritmo Ganancioso (Best-First Search).

    Args:
        estado_inicial (Estado): Estado inicial
        max_iter (int): Número máximo de iterações

    Returns:
        tuple: (custo, estado_final, stats) onde stats é um dicionário com
               métricas de desempenho
    """
    print("Executando Ganancioso...")
    inicio = time.time()

    # Fronteira: (heuristica, contador, estado)
    contador = 0
    fronteira = [(heuristica(estado_inicial), contador, estado_inicial)]
    heapq.heapify(fronteira)

    # Dicionários para controle
    veio_de = {}  # estado -> (estado_anterior, acao, peso)
    visitados = set()

    # Para calcular custo no final
    custos = {estado_inicial: 0}

    iteracoes = 0
    max_fronteira = 1

    while fronteira and iteracoes < max_iter:
        iteracoes += 1
        h_atual, _, estado_atual = heapq.heappop(fronteira)

        # Atualiza estatísticas
        max_fronteira = max(max_fronteira, len(fronteira))

        if estado_atual in visitados:
            continue

        visitados.add(estado_atual)

        # Verifica se é objetivo
        if eh_estado_objetivo(estado_atual):
            # Reconstrói caminho para calcular custo real
            custo_real = custos[estado_atual]
            fim = time.time()
            stats = {
                'iteracoes': iteracoes,
                'visitados': len(visitados),
                'max_fronteira': max_fronteira,
                'tempo': fim - inicio
            }
            return custo_real, estado_atual, stats

        # Gera sucessores
        for sucessor, acao, peso in gerar_sucessores(estado_atual):
            if sucessor not in visitados:
                # Calcula custo para este caminho
                custo_acao = 1 if acao == 'mover' else 1 + peso
                custos[sucessor] = custos[estado_atual] + custo_acao

                contador += 1
                heapq.heappush(fronteira, (heuristica(sucessor), contador, sucessor))
                veio_de[sucessor] = (estado_atual, acao, peso)

    fim = time.time()
    stats = {
        'iteracoes': iteracoes,
        'visitados': len(visitados),
        'max_fronteira': max_fronteira,
        'tempo': fim - inicio
    }
    return float('inf'), None, stats


def a_estrela(estado_inicial, max_iter=100000):
    """
    Algoritmo A*.

    Args:
        estado_inicial (Estado): Estado inicial
        max_iter (int): Número máximo de iterações

    Returns:
        tuple: (custo, estado_final, stats) onde stats é um dicionário com
               métricas de desempenho
    """
    print("Executando A*...")
    inicio = time.time()

    # Fronteira: (f = g + h, contador, estado)
    contador = 0
    f_inicial = 0 + heuristica(estado_inicial)
    fronteira = [(f_inicial, contador, estado_inicial)]
    heapq.heapify(fronteira)

    # Dicionários para controle
    g_custos = {estado_inicial: 0}  # custo real do caminho
    f_custos = {estado_inicial: f_inicial}
    veio_de = {}  # estado -> (estado_anterior, acao, peso)
    visitados = set()

    iteracoes = 0
    max_fronteira = 1

    while fronteira and iteracoes < max_iter:
        iteracoes += 1
        f_atual, _, estado_atual = heapq.heappop(fronteira)

        # Atualiza estatísticas
        max_fronteira = max(max_fronteira, len(fronteira))

        # Se já expandimos este estado, ignora
        if estado_atual in visitados:
            continue

        visitados.add(estado_atual)
        g_atual = g_custos[estado_atual]

        # Verifica se é objetivo
        if eh_estado_objetivo(estado_atual):
            fim = time.time()
            stats = {
                'iteracoes': iteracoes,
                'visitados': len(visitados),
                'max_fronteira': max_fronteira,
                'tempo': fim - inicio
            }
            return g_atual, estado_atual, stats

        # Gera sucessores
        for sucessor, acao, peso in gerar_sucessores(estado_atual):
            custo_acao = 1 if acao == 'mover' else 1 + peso
            novo_g = g_atual + custo_acao

            # Se encontrou caminho melhor para o sucessor
            if sucessor not in g_custos or novo_g < g_custos[sucessor]:
                g_custos[sucessor] = novo_g
                f = novo_g + heuristica(sucessor)
                f_custos[sucessor] = f

                contador += 1
                heapq.heappush(fronteira, (f, contador, sucessor))
                veio_de[sucessor] = (estado_atual, acao, peso)

    fim = time.time()
    stats = {
        'iteracoes': iteracoes,
        'visitados': len(visitados),
        'max_fronteira': max_fronteira,
        'tempo': fim - inicio
    }
    return float('inf'), None, stats


# =============================================================================
# FUNÇÕES DE SAÍDA
# =============================================================================

def salvar_resultado(nome_arquivo, algoritmo, estado_inicial, estado_final,
                     custo, stats, caminho_acoes=None):
    """
    Salva o resultado da execução em um arquivo.

    Args:
        nome_arquivo (str): Nome do arquivo de saída
        algoritmo (str): Nome do algoritmo usado
        estado_inicial (Estado): Estado inicial
        estado_final (Estado): Estado final (objetivo)
        custo (int): Custo total da solução
        stats (dict): Estatísticas da execução
        caminho_acoes (list): Lista de ações executadas
    """
    with open(nome_arquivo, 'w', encoding='utf-8') as f:
        f.write("=" * 60 + "\n")
        f.write(f"ALGORITMO: {algoritmo.upper()}\n")
        f.write("=" * 60 + "\n\n")

        f.write("ESTADO INICIAL:\n")
        f.write("-" * 40 + "\n")
        f.write(str(estado_inicial))
        f.write("\n\n")

        if estado_final:
            f.write("ESTADO FINAL (OBJETIVO):\n")
            f.write("-" * 40 + "\n")
            f.write(str(estado_final))
            f.write("\n\n")

            f.write("RESULTADOS:\n")
            f.write("-" * 40 + "\n")
            f.write(f"Custo total da solução: {custo}\n")
            f.write(f"Número de iterações: {stats['iteracoes']}\n")
            f.write(f"Estados visitados: {stats['visitados']}\n")
            f.write(f"Tamanho máximo da fronteira: {stats['max_fronteira']}\n")
            f.write(f"Tempo de execução: {stats['tempo']:.4f} segundos\n")

            if caminho_acoes:
                f.write(f"\nSEQUÊNCIA DE AÇÕES ({len(caminho_acoes)} passos):\n")
                for i, (acao, peso) in enumerate(caminho_acoes, 1):
                    if acao == 'mover':
                        f.write(f"  {i}. Mover agente (custo 1)\n")
                    else:
                        f.write(f"  {i}. Empurrar caixa de peso {peso} (custo {1+peso})\n")
        else:
            f.write("NENHUMA SOLUÇÃO ENCONTRADA!\n")
            f.write(f"Limite de iterações: {stats['iteracoes']}\n")
            f.write(f"Estados visitados: {stats['visitados']}\n")
            f.write(f"Tempo de execução: {stats['tempo']:.4f} segundos\n")


def gerar_arquivos_saida(estado_inicial, resultados):
    """
    Gera os três arquivos de saída (dijkstra.txt, ganancioso.txt, a_estrela.txt).

    Args:
        estado_inicial (Estado): Estado inicial do problema
        resultados (dict): Dicionário com resultados de cada algoritmo
    """
    for algoritmo in ['dijkstra', 'ganancioso', 'a_estrela']:
        if algoritmo in resultados:
            custo, estado_final, stats, caminho = resultados[algoritmo]
            nome_arquivo = f"{algoritmo}.txt"
            salvar_resultado(
                nome_arquivo, algoritmo, estado_inicial,
                estado_final, custo, stats, caminho
            )
            print(f"Arquivo gerado: {nome_arquivo}")


# =============================================================================
# FUNÇÃO PRINCIPAL
# =============================================================================

def main():
    """
    Função principal do programa.

    Uso:
        python solucao.py entrada.txt
    """
    if len(sys.argv) != 2:
        print("Uso: python solucao.py entrada.txt")
        sys.exit(1)

    arquivo_entrada = sys.argv[1]

    try:
        print(f"\n{'='*60}")
        print("SOKOBAN PONDERADO - ALGORITMOS DE BUSCA")
        print(f"{'='*60}\n")

        print(f"Lendo arquivo: {arquivo_entrada}")
        estado_inicial = ler_arquivo(arquivo_entrada)

        print("\nEstado inicial carregado:")
        print("-" * 40)
        print(estado_inicial)
        print("-" * 40)
        print(f"Número de caixas: {len(estado_inicial.caixas)}")
        print(f"Pesos das caixas: {[p for _, _, p in estado_inicial.caixas]}")
        print(f"Número de alvos: {len(estado_inicial.alvos)}")

        # Executa Dijkstra
        print("\n" + "-" * 40)
        custo_d, estado_final_d, stats_d = dijkstra(estado_inicial)

        # Executa Ganancioso
        print("\n" + "-" * 40)
        custo_g, estado_final_g, stats_g = ganancioso(estado_inicial)

        # Executa A*
        print("\n" + "-" * 40)
        custo_a, estado_final_a, stats_a = a_estrela(estado_inicial)

        print("\n" + "=" * 60)
        print("RESUMO DOS RESULTADOS")
        print("=" * 60)

        # Tabela comparativa
        print("\n{:<15} {:>12} {:>12} {:>15} {:>12}".format(
            "Algoritmo", "Custo", "Visitados", "Max Fronteira", "Tempo(s)"))
        print("-" * 70)

        if estado_final_d:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "Dijkstra", custo_d, stats_d['visitados'],
                stats_d['max_fronteira'], stats_d['tempo']))
        else:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "Dijkstra", "INF", stats_d['visitados'],
                stats_d['max_fronteira'], stats_d['tempo']))

        if estado_final_g:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "Ganancioso", custo_g, stats_g['visitados'],
                stats_g['max_fronteira'], stats_g['tempo']))
        else:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "Ganancioso", "INF", stats_g['visitados'],
                stats_g['max_fronteira'], stats_g['tempo']))

        if estado_final_a:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "A*", custo_a, stats_a['visitados'],
                stats_a['max_fronteira'], stats_a['tempo']))
        else:
            print("{:<15} {:>12} {:>12} {:>15} {:.4f}".format(
                "A*", "INF", stats_a['visitados'],
                stats_a['max_fronteira'], stats_a['tempo']))

        # Prepara resultados para salvar
        resultados = {}

        if estado_final_d:
            # Reconstrói caminho para Dijkstra
            # Nota: Para simplificar, não estamos reconstruindo o caminho completo
            # Em uma implementação completa, você precisaria armazenar os pais
            resultados['dijkstra'] = (custo_d, estado_final_d, stats_d, [])

        if estado_final_g:
            resultados['ganancioso'] = (custo_g, estado_final_g, stats_g, [])

        if estado_final_a:
            resultados['a_estrela'] = (custo_a, estado_final_a, stats_a, [])

        # Gera arquivos de saída
        print("\n" + "-" * 40)
        print("Gerando arquivos de saída...")
        gerar_arquivos_saida(estado_inicial, resultados)

        print("\n" + "=" * 60)
        print("PROCESSAMENTO CONCLUÍDO!")
        print("=" * 60)

    except FileNotFoundError:
        print(f"Erro: Arquivo '{arquivo_entrada}' não encontrado!")
        sys.exit(1)
    except Exception as e:
        print(f"Erro durante a execução: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()